version: '3.8'

services:
  produk-service:
    build: ./produk-service
    container_name: produk-service
    ports:
      - "3001:3001"
    networks:
      - ecom-network

  pesanan-service:
    build: ./pesanan-service
    container_name: pesanan-service
    ports:
      - "3002:3002"
    environment:
      - PRODUCT_SERVICE_URL=http://produk-service:3001
    depends_on:
      - produk-service
    networks:
      - ecom-network

  # === TAMBAHKAN SERVIS AKUN DI SINI ===
  akun-service:
    build: ./akun-service
    container_name: akun-service
    ports:
      - "3003:3003"
    networks:
      - ecom-network

  # === TAMBAHKAN SERVIS KERANJANG DI SINI ===
  keranjang-service:
    build: ./keranjang-service
    container_name: keranjang-service
    ports:
      - "3004:3004"
    networks:
      - ecom-network

  # === TAMBAHKAN SERVIS PAYMENT DI SINI ===
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "3005:3005"
    networks:
      - ecom-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - PRODUCT_SERVICE_URL=http://produk-service:3001
      - ORDER_SERVICE_URL=http://pesanan-service:3002
      - ACCOUNT_SERVICE_URL=http://akun-service:3003
      - CART_SERVICE_URL=http://keranjang-service:3004
      - PAYMENT_SERVICE_URL=http://payment-service:3005
    depends_on:
      - produk-service
      - pesanan-service
      - akun-service
      - keranjang-service
      - payment-service
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge